; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src
include_dir = include
default_envs = SOUND_MATRIX_16x16


[env]
lib_deps = fastled/FastLED
					 arduinolib=https://github.com/shtein/arduinolib.git#master
monitor_speed = 57600
monitor_echo = yes
build_type = release


;------------- Boards --------------
[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_speed = 115200

[env:pro16MHzatmega328]
platform = atmelavr
board = pro16MHzatmega328 
framework = arduino
upload_speed = 57600

[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
upload_speed = 115200

[env:promicro_5v]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
monitor_speed = 115200
upload_speed = 115200 

[env:nano_every]
platform  = atmelmegaavr
board     = nano_every
framework = arduino
monitor_speed = 57600
upload_speed = 115200

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
upload_speed = 115200
platform_packages = platform_packages = toolchain-xtensa                   
                    platformio/tool-esptool @ ~1.413.0
                    platformio/tool-esptoolpy @ ~1.30000.0
build_flags = -Wno-deprecated-declarations
              -Wno-misleading-indentation
board_build.filesystem = littlefs                                                      

;------------ Builds ----------------

[env:OUTAGE_LAMP]
extends = env:pro16MHzatmega328
build_flags = 
	-D__OUTAGE_LAMP_SETUP
  -DSETUP_NAME=\"Outage\ Lamp\"
	-DMAX_LEDS=31
  

[env:DAVID]
extends = env:pro16MHzatmega328
build_flags = 
	-D__DAVID_SETUP
  -DSETUP_NAME="David"
  -DMAX_LEDS=50
  -DDBG_TO_SERIAL
  -DNTF_ENABLED
	

[env:IGOR]
extends = env:uno
build_flags = 
	-D__IGOR_SETUP 
  -DSETUP_NAME=\"Igor\"
  -DUSE_IR_REMOTE
	-DMAX_LEDS=88

[env:DECK]
extends = env:pro16MHzatmega328
build_flags = 
	-D__DECK_SETUP
  -DSETUP_NAME="Deck"
	-DMAX_LEDS=266
  ;-DWRITE_CONFIG_ONLY
  -DNO_EFFECT_FIRE -DNO_EFFECT_RAINBOW_MOVE -DNO_EFFECT_RAINBOW -DNO_EFFECT_THEATER_CHASE_RAINBOW 
  -DNO_EFFECT_EMERGENCY_LIGHTS -DNO_EFFECT_COLOR_WIPE -DNO_EFFECT_STATIC_COLOR -DNO_EFFECT_JUGGLE -DNO_EFFECT_PALLETE_TRANSFORM 
  -DNO_PALLETE_PORTUGAL_FLAG -DNO_PALLETE_ISRAEL_FLAG
  -DSERIAL_BINARY_ENABLED
  -DNTF_BINARY_ENABLED
  ;-DDBG_TO_SERIAL
  ;-DSERIAL_ENABLED
  ;-DNTF_ENABLED
;monitor_filters = tx_hex, send_on_enter
;monitor_echo = yes                  
;monitor_encoding = Latin1               

[env:CHRISTMASS_TREE]
extends = env:pro16MHzatmega328
build_flags = 
	-D__CHRISTMAS_TREE_SETUP
  -DSETUP_NAME="Chrsitmas Tree"
	-DMAX_LEDS=150

[env:WINDOW]
extends = env:pro16MHzatmega328
build_flags = 
	-D__WINDOW_SETUP  
  -DSETUP_NAME="Window"
  -DNO_EFFECT_PALLETE_TRANSFORM -DNO_EFFECT_RAINBOW -DNO_EFFECT_RAINBOW_MOVE
  -DNO_EFFECT_THEATER_CHASE_RAINBOW -DNO_EFFECT_EMERGENCY_LIGHTS -DNO_EFFECT_FIRE
  -DNO_EFFECT_COLOR_WIPE -DNO_EFFECT_STATIC_COLOR -DNO_EFFECT_RIPPLE -DNO_EFFECT_RUNNING_LIGHTS  
	-DMAX_LEDS=100
  -DDBG_TO_SERIAL
  -DNTF_ENABLED
  ;-DWRITE_CONFIG_ONLY

[env:VADIM]
extends = env:pro16MHzatmega328
build_flags = 
	-D__VADIM_SETUP
  -DSETUP_NAME=\"Vadim\"
  ;-DWRITE_CONFIG_ONLY
	-DMAX_LEDS=100

[env:TAHOE]
extends = env:promicro_5v
build_flags = 
	-D__TAHOE_SETUP
  -DSETUP_NAME=\"Tahoe\"
  -DWRITE_CONFIG_ONLY
  -DNO_EFFECT_PALLETE_TRANSFORM -DNO_EFFECT_RAINBOW -DNO_EFFECT_RAINBOW_MOVE -DNO_EFFECT_THEATER_CHASE_RAINBOW
  -DNO_EFFECT_EMERGENCY_LIGHTS -DNO_EFFECT_COLOR_WIPE -DNO_EFFECT_RUNNING_LIGHTS -DNO_EFFECT_FIRE 
  -DNO_EFFECT_FADE_INOUT -DNO_EFFECT_METEOR_RAIN -DNO_EFFECT_BLUR -DNO_EFFECT_STATIC_COLOR
  -DNO_PALLETE_PORTUGAL_FLAG -DNO_PALLETE_ISRAEL_FLAG
	-DMAX_LEDS=417   
  -DRIPPLE_COUNT=10
  -DSERIAL_BINARY_ENABLED
  -DNTF_BINARY_ENABLED
  ;-DDBG_TO_SERIAL
  ;-DNTF_ENABLED
;monitor_filters = tx_hex, send_on_enter
;monitor_echo    = yes                  
;monitor_encoding  = Latin1                 
  
[env:SASHA]
extends = env:pro16MHzatmega328
build_flags = 
	-D__SASHA_SETUP 
  -DSETUP_NAME=\"Sasha\"
  ;-DUSE_IR_REMOTE
	-DMAX_LEDS=212  
  ;-DWRITE_CONFIG_ONLY
  -DSERIAL_BINARY_ENABLED -DNTF_BINARY_ENABLED

[env:SASHA_TAHOE]
extends = env:pro16MHzatmega328
build_flags = 
	-D__SASHA_TAHOE_SETUP
  -DSETUP_NAME=\"Sasha\ Tahoe\"
  ;-DWRITE_CONFIG_ONLY
	-DMAX_LEDS=104
  ;-DDBG_TO_SERIAL
  -DSERIAL_BINARY_ENABLED -DNTF_BINARY_ENABLED 


[env:UDALOV]
extends = env:pro16MHzatmega328
build_flags = 
	-D__UDALOV_SETUP
  -DSETUP_NAME=\"Udalov\"
	-DMAX_LEDS=200
  ;-DWRITE_CONFIG_ONLY

[env:ALL_PURPOSE]
extends = env:pro16MHzatmega328
build_flags = 
	-D__ALL_PURPOSE_SETUP
  -DSETUP_NAME=\"All\ purpose\"
	-DMAX_LEDS=300
  ;-DWRITE_CONFIG_ONLY
  ;-DDBG_TO_SERIAL
  ;-DNTF_ENABLED

[env:MEDIA_ROOM]
extends =  env:pro16MHzatmega328
build_flags =   
	-D__MEDIA_ROOM_SETUP 
  -DSETUP_NAME=\"Media\ Room\"
  -DUSE_SOUND -DSOUND_ONLY
  ;-DWRITE_CONFIG_ONLY
  -DNTF_ENABLED
	-DDBG_TO_SERIAL
	-DMAX_LEDS=49
	
[env:SOUND_MATRIX_16x16]
extends = env:pro16MHzatmega328
build_flags = 
  -D__SOUND_MATRIX_16x16
  -DSETUP_NAME=\"Sound\ Matrix\"  
  -DUSE_SOUND -DSOUND_ONLY -DNO_SOUND_COMMANDS
  -DEFFECT_TWINKLE_FOX -DEFFECT_NOISE -DEFFECT_MATRIX_BOUNCING_DOTS
  -DNO_PALLETE_JULY4TH -DNO_PALLETE_SNOW_AND_ICE -DNO_PALLETE_PLASMA 
  -DNO_PALLETE_VALENTINES -DNO_PALLETET_PORTUGAL_FLAG -DNO_PALLETE_ISRAEL_FLAG  
  -DNO_PALLETE_HALLOWEEN -DNO_PALLETE_AUTUMN -DNO_PALLETE_CHRISTMAS
  ;-DWRITE_CONFIG_ONLY
  ;-DSERIAL_ENABLED -DNTF_ENABLED   
  ;-DSERIAL_BINARY_ENABLED -DNTF_BINARY_ENABLED 
  ;-DDBG_TO_SERIAL
  -DBRIGHTNESS=192
  -DUSE_MATRIX -DMATRIX_WIDTH=16 -DMATRIX_HEIGHT=16 -DMATRIX_TYPE=xyMatrixSerpent
monitor_filters = rx_hex, send_on_enter
monitor_echo = yes                  
monitor_encoding = Latin1               


[env:FRAME_MATRIX_16x16]
extends = env:pro16MHzatmega328
build_flags = 
	-D__FRAME_MATRIX_16x16
  -DSETUP_NAME=\"Maxtrix\ 16x16\"
	-DDBG_TO_SERIAL  
  ;-DNTF_ENABLED
  ;-DWRITE_CONFIG_ONLY
  -DNO_EFFECT_PALLETE_TRANSFORM
  -DNO_EFFECT_RAINBOW
  -DNO_EFFECT_RAINBOW_MOVE
  -DNO_EFFECT_THEATER_CHASE_RAINBOW
  -DNO_EFFECT_EMERGENCY_LIGHTS
  -DNO_EFFECT_COLOR_WIPE
  -DNO_EFFECT_STATIC_COLOR
  -DNO_EFFECT_RIPPLE
  -DNO_EFFECT_RUNNING_LIGHTS
  -DNO_EFFECT_FIRE
  -DNO_EFFECT_THEATER_CHASE_RAINBOW
	-DUSE_MATRIX
	-DMATRIX_WIDTH=16
	-DMATRIX_HEIGHT=16
	-DMATRIX_TYPE=xyMatrixSerpent

[env:TEST]
extends = env:uno
build_flags = ;${env:esp01_1m.build_flags}
  ;-DUSE_IR_REMOTE
	-D__TEST
  -DSETUP_NAME=\"Test\"
	-DDBG_TO_SERIAL
  ;-DNTF_ENABLED -DSERIAL_ENABLED
  -DSERIAL_BINARY_ENABLED -DNTF_BINARY_ENABLED 
  ;-DWRITE_CONFIG_ONLY
  -DNO_EFFECT_PALLETE_TRANSFORM
  -DNO_EFFECT_RAINBOW
  -DNO_EFFECT_RAINBOW_MOVE
  -DNO_EFFECT_THEATER_CHASE_RAINBOW
  -DNO_EFFECT_RUNNING_LIGHTS
  -DNO_EFFECT_EMERGENCY_LIGHTS
	-DMAX_LEDS=150 
;monitor_filters = tx_hex, send_on_enter
;monitor_echo = yes                  
;monitor_encoding = Latin1               

  
;------------- Native --------------
; Only for tests
[env:native] 
platform = native
test_filter = test*
lib_deps = arduinolib=https://github.com/shtein/arduinolib.git#master
lib_ignore = arduinolib
build_flags = -I$PROJECT_LIBDEPS_DIR/$PIOENV/arduinolib/include